In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['English' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]
 ['English' 21.0 24000.0]
 ['Spain' nan nan]
 ['Spain' 28.0 52000.0]
 ['France' 25.0 32000.0]
 ['Indonesia' 21.0 12000.0]
 ['Indonesia' 43.0 21000.0]
 ['Indonesia' 57.0 26000.0]
 ['Germany' 27.0 43000.0]
 [nan nan 52000.0]]


In [4]:
print(y)

['Yes' 'Yes' 'No' 'No' 'Yes' 'No' 'No' 'Yes' 'No' 'Yes' 'Yes' 'No' 'Yes'
 'No' 'No' 'Yes' 'Yes' 'No' 'Yes']


In [5]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['English' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]
 ['English' 21.0 24000.0]
 ['Spain' nan nan]
 ['Spain' 28.0 52000.0]
 ['France' 25.0 32000.0]
 ['Indonesia' 21.0 12000.0]
 ['Indonesia' 43.0 21000.0]
 ['Indonesia' 57.0 26000.0]
 ['Germany' 27.0 43000.0]
 [nan nan 52000.0]]


In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder ##pengubahan dari nominal ke numerik
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough') 
x = np.array(ct.fit_transform(x))

In [7]:
print(x)

[[0.0 1.0 0.0 0.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 27.0 48000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 38.0 61000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 40.0 nan]
 [0.0 1.0 0.0 0.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 nan 52000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 37.0 67000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 21.0 24000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 nan nan]
 [0.0 0.0 0.0 0.0 1.0 0.0 28.0 52000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 25.0 32000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 21.0 12000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 43.0 21000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 57.0 26000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 27.0 43000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 nan 52000.0]]


In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [9]:
print(y)

[1 1 0 0 1 0 0 1 0 1 1 0 1 0 0 1 1 0 1]


In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1) ##80 20 perbandingannya

In [11]:
print(x_train)

[[0.0 0.0 1.0 0.0 0.0 0.0 30.0 54000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 21.0 12000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 40.0 nan]
 [0.0 0.0 0.0 1.0 0.0 0.0 57.0 26000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 25.0 32000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 nan 52000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 27.0 43000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 50.0 83000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 28.0 52000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 nan nan]
 [0.0 1.0 0.0 0.0 0.0 0.0 35.0 58000.0]]


In [12]:
print(x_test)

[[1.0 0.0 0.0 0.0 0.0 0.0 38.0 61000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 43.0 21000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 nan 52000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 21.0 24000.0]]


In [13]:
print(y_train)

[0 0 1 1 1 1 0 1 1 0 1 0 1 0 0]


In [14]:
print(y_test)

[0 1 0 1]


In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:]) ## mulai ketiga sampai selesai
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [16]:
print(x_train)

[[0.0 0.0 1.0 -0.3922322702763682 -0.5 -0.26726124191242434
  -0.571295014798562 0.0929562482375909]
 [0.0 0.0 0.0 2.5495097567963936 -0.5 -0.26726124191242434
  -1.4173901632976977 -2.0217983991676047]
 [0.0 0.0 1.0 -0.3922322702763682 -0.5 -0.26726124191242434
  0.3688107057560332 nan]
 [0.0 0.0 0.0 2.5495097567963936 -0.5 -0.26726124191242434
  1.966990430698845 -1.3168801833658728]
 [0.0 1.0 0.0 -0.3922322702763682 -0.5 -0.26726124191242434
  1.1208952821997094 1.351738776454969]
 [0.0 0.0 0.0 -0.3922322702763682 2.0 -0.26726124191242434
  -0.8533267309649405 -0.20915155853457987]
 [0.0 1.0 0.0 -0.3922322702763682 -0.5 -0.26726124191242434
  -1.0413478750758596 -1.014772376593702]
 [0.0 1.0 0.0 -0.3922322702763682 -0.5 -0.26726124191242434
  0.7448529939778713 0.9992796685541032]
 [0.0 0.0 0.0 -0.3922322702763682 -0.5 3.741657386773941 nan
  -0.007746354019799363]
 [0.0 0.0 1.0 -0.3922322702763682 -0.5 -0.26726124191242434
  -0.8533267309649405 -0.4609080641780555]
 [0.0 1.0 0.0 -0

In [17]:
print(x_test) 

[[1.0 0.0 0.0 -0.3922322702763682 -0.5 -0.26726124191242434
  0.18078956164511414 0.4454153561384568]
 [0.0 0.0 0.0 2.5495097567963936 -0.5 -0.26726124191242434
  0.6508424219224117 -1.5686366890093484]
 [0.0 0.0 0.0 -0.3922322702763682 2.0 -0.26726124191242434 nan
  -0.007746354019799363]
 [1.0 0.0 0.0 -0.3922322702763682 -0.5 -0.26726124191242434
  -1.4173901632976977 -1.417582785623263]]
